#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/aquaponics2021_0_0_8v.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/jssc.jar" aquaponics2021_0_0_8v "$@"
